# use new docker environment
sudo: required

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - git
      - libc6-i386
      - cppcheck
      - clang-3.7
      - g++-5
      - gcc-5
      - gcov-5
      - lcov
      - genhtml

# We use cpp for unit tests, and c for the main project.
language: cpp
compiler: gcc

before_install:
  - curl --retry 10 --retry-max-time 120 -L "https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q2-update/+download/gcc-arm-none-eabi-4_9-2015q2-20150609-linux.tar.bz2" | tar xfj -
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 50
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 50

install:
  - export PATH=$PATH:$PWD/gcc-arm-none-eabi-4_9-2015q2/bin

before_script: 
        - arm-none-eabi-gcc --version
        - gcov --version        
script: 
        - cd project 
        - ./configure
        - make test 
        - make clean 
        - make firmware 
        - make clean 
        - make debug_firmware
